import { describe, it, expect } from 'vitest';
import { addItem, updateItem, listItemsByRoom, isWarrantyExpiring, warrantyStatus, SyncQueue } from '../../src/lib/domain/inventory';
import { createSchedule, createWorkOrder, updateWorkOrderStatus, listMaintenanceHistory, isOverdue } from '../../src/lib/domain/maintenance';
import { spendingByCategory, utilityConsumptionPattern, budgetAlerts, type Transaction, type Utility, type UtilityReading } from '../../src/lib/domain/analytics';
import type { Property, Item } from '../../src/lib/domain/property';

describe('Operations and Domain Flow Integrations', () => {
  it('should trigger maintenance work orders when inventory warranties are expiring', () => {
    // Setup a property with inventory items
    let property: Property = {
      id: 'prop-operations-1',
      name: 'NIDO Headquarters',
      floors: [],
      items: []
    };

    const expiringWarrantyDate = new Date();
    expiringWarrantyDate.setDate(expiringWarrantyDate.getDate() + 10); // expires in 10 days

    // Add a critical dishwasher item with expiring warranty
    property = addItem(property, {
      name: 'Industrial Dishwasher',
      roomId: 'kitchen-main',
      value: 1200,
      warrantyUntil: expiringWarrantyDate.toISOString().split('T')[0]
    });

    const items = listItemsByRoom(property, 'kitchen-main');
    expect(items.length).toEqual(1);
    const dishwasher = items[0];

    // Verify warranty status is soon
    expect(warrantyStatus(dishwasher)).toEqual('soon');
    expect(isWarrantyExpiring(dishwasher, 30)).toEqual(true);

    // Automatically trigger a maintenance work order/schedule due to warranty expiration check
    let workOrder = null;
    if (isWarrantyExpiring(dishwasher, 15)) {
      const schedule = createSchedule(dishwasher.id, 90, new Date());
      workOrder = createWorkOrder(schedule, {
        assignee: 'Dishwasher Experts Corp',
        notes: `Urgent preventive maintenance before warranty expires on ${dishwasher.warrantyUntil}`
      });
    }

    expect(workOrder).not.toBeNull();
    expect(workOrder?.itemId).toEqual(dishwasher.id);
    expect(workOrder?.notes).toContain('before warranty expires');
    expect(workOrder?.status).toEqual('open');
  });

  it('should generate financial costs and transactions when maintenance work orders are completed, feedable to analytics', () => {
    let property: Property = {
      id: 'prop-operations-2',
      name: 'NIDO Mansion',
      floors: [],
      items: [],
      workOrders: []
    };

    // Add HVAC system to inventory
    property = addItem(property, {
      name: 'Central HVAC System',
      roomId: 'basement-mech',
      value: 8500
    });

    const hvac = property.items![0];

    // Create a maintenance schedule and open a work order
    const schedule = createSchedule(hvac.id, 180, new Date());
    let workOrder = createWorkOrder(schedule, {
      assignee: 'HVAC Solutions',
      notes: 'Bi-annual filter replacement and coolant check'
    });

    property.workOrders?.push(workOrder);

    // Complete the work order
    workOrder = updateWorkOrderStatus(workOrder, 'done');

    // Simulate invoice cost generated by completion of work order
    const serviceCost = 250;
    const replacementPartCost = 75; // Replacement part filter from inventory

    // Register these transactions into the transaction pool for analytics
    const transactions: Transaction[] = [
      {
        id: 'tx-wo-service',
        category: 'Maintenance',
        amount: serviceCost,
        date: new Date(),
        description: `Service fee for completed work order ${workOrder.id}`
      },
      {
        id: 'tx-wo-parts',
        category: 'Maintenance',
        amount: replacementPartCost,
        date: new Date(),
        description: `Replacement parts for completed work order ${workOrder.id}`
      }
    ];

    // Perform financial analytics on generated transactions
    const summaries = spendingByCategory(transactions);
    expect(summaries.length).toEqual(1);
    expect(summaries[0].category).toEqual('Maintenance');
    expect(summaries[0].total).toEqual(serviceCost + replacementPartCost);
  });

  it('should integrate utility consumption patterns with maintenance spending to generate comprehensive budget alerts', () => {
    // Define utility and reading
    const waterUtility: Utility = {
      id: 'util-water-main',
      name: 'Water',
      monthlyBudget: 300
    };

    // High consumption reading
    const readings: UtilityReading[] = [
      { id: 'r1', utilityId: 'util-water-main', reading: 350, date: new Date() }
    ];

    // Maintenance transaction on water pipes
    const transactions: Transaction[] = [
      { id: 'tx-pipe-repair', category: 'Water', amount: 150, date: new Date(), description: 'Emergency pipe leak fix' }
    ];

    // Compute pattern metrics
    const pattern = utilityConsumptionPattern(waterUtility, readings);
    expect(pattern.max).toEqual(350);

    // Generate budget alerts based on utility thresholds and transactions
    const alerts = budgetAlerts([waterUtility], transactions, readings);

    // There should be alerts both for exceeding transaction budgets and high consumption thresholds
    expect(alerts.length).toEqual(1);
    expect(alerts[0]).toContain('High consumption alert for Water');
  });

  it('should sync offline inventory actions using SyncQueue and trigger corresponding maintenance scheduling upon sync', async () => {
    const syncQueue = new SyncQueue();
    let property: Property = {
      id: 'prop-sync-test',
      name: 'Offline Cabin',
      floors: [],
      items: []
    };

    // Offline additions
    const generatorId = 'generator-id-999';
    syncQueue.enqueue('add', generatorId, {
      name: 'Backup Diesel Generator',
      roomId: 'garage',
      value: 1500
    });

    const queuedOps = syncQueue.getQueue();
    expect(queuedOps.length).toEqual(1);
    expect(queuedOps[0].action).toEqual('add');

    // Simulate sync processor
    const syncResult = await syncQueue.process(async (op) => {
      if (op.action === 'add') {
        property = addItem(property, {
          id: op.itemId,
          name: op.payload.name,
          roomId: op.payload.roomId,
          value: op.payload.value
        });
        return true;
      }
      return false;
    });

    expect(syncResult.success).toEqual(true);
    expect(syncResult.processedCount).toEqual(1);
    expect(property.items?.length).toEqual(1);

    // Now schedule a periodic maintenance check for the synced generator
    const syncedItem = property.items![0];
    const maintenanceSchedule = createSchedule(syncedItem.id, 30, new Date());

    expect(maintenanceSchedule.itemId).toEqual(generatorId);
    expect(maintenanceSchedule.interval_days).toEqual(30);
  });
});
